# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py

sudo: false
language: python
python: 2.7

install:
  - pip install tox

env:
  - TOX_ENV=flake8
  - TOX_ENV=tests

script:
  - tox -e $TOX_ENV
