# docker-compose for antenna development.
#
# Note: Requires docker 1.10.0+ and docker-compose 1.6.0+.
version: "2"
services:
  # This builds an image of the deploy base. Then we extend that with
  # dev-related things to do our dev-y stuff.
  deploy-base:
    build:
      context: .
      dockerfile: Dockerfile
    image: local/antenna_deploy_base

  # This builds an image that extends Dockerfile with dev-related things.
  dev-base:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: local/antenna_dev

  # ------------------------------------------------------------------
  # After this point is dev-related services.
  # ------------------------------------------------------------------

  # Base container is used for development tasks like tests, linting, coverage
  # and building docs.
  base:
    image: local/antenna_dev
    environment:
      - COVERAGE_FILE=/tmp/.coverage
    volumes:
      - .:/app

  # Web container is a prod-like fully-functioning Antenna container.
  web:
    extends:
      service: base
    environment:
      - ANTENNA_ENV=${ANTENNA_ENV}
    ports:
      - "8000:8000"
    command: ./bin/run_web.sh
    links:
      - moto-s3
      - statsd

  # System test container
  systemtest:
    extends:
      service: base
    environment:
      - ANTENNA_ENV=${ANTENNA_ENV}
      - POSTURL=http://web:8000/submit
      - NONGINX=1
    links:
      - web

  # moto-server running a fake S3
  moto-s3:
    build:
      context: .
      dockerfile: Dockerfile.motos3
    command: s3 -H 0.0.0.0 -p5000
    ports:
      - "5000:5000"

  # https://hub.docker.com/r/kamon/grafana_graphite/
  # username: admin, password: admin
  statsd:
    image: kamon/grafana_graphite
    ports:
      - "9000:3000"  # grafana port
