# docker-compose for antenna development.
#
# Note: Requires docker 1.10.0+ and docker-compose 1.6.0+.
version: "2"
services:
  # This builds an image of the deploy base. Then we extend that with
  # dev-related things to do our dev-y stuff.
  deploy-base:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: local/antenna_deploy_base

  # ------------------------------------------------------------------
  # After this point is dev-related services.
  # ------------------------------------------------------------------

  # Base container is used for development tasks like tests, linting, coverage
  # and building docs.
  base:
    image: local/antenna_deploy_base
    environment:
      - COVERAGE_FILE=/tmp/.coverage
    volumes:
      - .:/app

  # Web container is a prod-like fully-functioning Antenna container.
  web:
    extends:
      service: base
    env_file:
      - docker/config/local_dev.env
      - my.env
    ports:
      - "8000:8000"
    command: ./bin/run_web.sh
    links:
      - localstack-s3
      - statsd

  # System test container
  systemtest:
    extends:
      service: base
    env_file:
      - docker/config/local_dev.env
      - my.env
    environment:
      - POSTURL=http://web:8000/submit
      - NONGINX=1
    links:
      - web

  # https://hub.docker.com/r/localstack/localstack/
  # localstack running a fake S3
  localstack-s3:
    image: localstack/localstack:0.8.4
    environment:
      - SERVICES=s3:5000
      - DEFAULT_REGION=us-east-1
      - HOSTNAME=localstack-s3
    ports:
      - "5000:5000"

  # https://hub.docker.com/r/kamon/grafana_graphite/
  # username: admin, password: admin
  statsd:
    image: kamon/grafana_graphite
    ports:
      - "9000:3000"  # grafana port
