# docker-compose for antenna development.
#
# Note: Requires docker 1.10.0+ and docker-compose 1.6.0+.
version: "2"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ANTENNA_INI=settings_dev.ini
    volumes:
      - .:/app
    ports:
      - "8000:8000"
