# docker-compose for antenna development.
#
# Note: Requires docker 1.10.0+ and docker-compose 1.6.0+.
version: "2"
services:
  # This builds an image of the deploy base. Then we extend that with
  # dev-related things to do our dev-y stuff.
  deploy-base:
    build:
      context: .
      dockerfile: Dockerfile
    image: local/antenna_deploy_base

  # This builds an image that extends Dockerfile with dev-related things.
  dev-base:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: local/antenna_dev

  # ------------------------------------------------------------------
  # After this point is dev-related services.
  # ------------------------------------------------------------------
  base:
    image: local/antenna_dev
    volumes:
      - .:/app
    environment:
      - ANTENNA_ENV=${ANTENNA_ENV}

  # This is the base web-service.
  web:
    extends:
      service: base
    ports:
      - "8000:8000"
    command: ./bin/run_web.sh
    links:
      - fakes3

  # fakes3 service
  # https://hub.docker.com/r/lphoward/fake-s3/
  fakes3:
    image: lphoward/fake-s3
    ports:
      - "4569:4569"
    volumes:
      - ./fakes3_root:/fakes3_root
