version: 2
jobs:
  build_test_push:
    docker:
      - image: docker:stable
    environment:
      APP_NAME: "socorro_collector"
    steps:
      - run:
          name: Install checkout deps
          command: |
            set -x
            apk update
            apk add git openssh

      - checkout
      - setup_remote_docker

      - run:
          name: Create version.json
          command: |
            # create a version.json per https://github.com/mozilla-services/Dockerflow/blob/master/docs/version_object.md
            printf '{"commit":"%s","version":"%s","source":"https://github.com/%s/%s","build":"%s"}\n' \
            "$CIRCLE_SHA1" \
            "$CIRCLE_TAG" \
            "$CIRCLE_PROJECT_USERNAME" \
            "$CIRCLE_PROJECT_REPONAME" \
            "$CIRCLE_BUILD_URL" > version.json

      - run:
          name: Build Docker image
          command: |
            docker info
            docker build -t ${APP_NAME}:build .

      - run:
          name: Run tests in Docker image
          command: |
            docker run ${APP_NAME}:build py.test
            docker run ${APP_NAME}:build flake8
            docker run ${APP_NAME}:build bandit -r antenna/

      - run:
          name: Push to Dockerhub
          command: |
            function retry {
                set +e
                local n=0
                local max=3
                while true; do
                "$@" && break || {
                  if [[ $n -lt $max ]]; then
                    ((n++))
                    echo "Command failed. Attempt $n/$max:"
                  else
                    echo "Failed after $n attempts."
                    exit 1
                  fi
                }
                done
                set -e
            }

            # tag images with SHA1 hash or git tag
            export DOCKER_IMAGE="mozilla/${APP_NAME}:${CIRCLE_SHA1}"
            if [ -n "${CIRCLE_TAG}" ]; then
                export DOCKER_IMAGE="mozilla/${APP_NAME}:${CIRCLE_TAG}"
            fi

            # push on master or git tag
            if [ "${CIRCLE_BRANCH}" == "master" ] || [ -n "${CIRCLE_TAG}" ]; then
                echo "${DOCKER_PASSWORD}" | docker login -u="${DOCKER_USERNAME}" --password-stdin
                retry docker tag "${APP_NAME}:build" "${DOCKER_IMAGE}"
                retry docker push "${DOCKER_IMAGE}"
            fi

workflows:
  version: 2

  # workflow jobs are _not_ run in tag builds by default
  # we use filters to whitelist jobs that should be run for tags

  # workflow jobs are run in _all_ branch builds by default
  # we use filters to blacklist jobs that shouldn't be run for a branch

  # see: https://circleci.com/docs/2.0/workflows/#git-tag-job-execution

  build_test_push:
    jobs:
      - build_test_push:
          filters:
            tags:
              only: /.*/
